version: "3.8"
services:
  database:
    image: mysql:8.0.20
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tqs_hw1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
      - db_file:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 20
    networks:
      - backend

  backend:
    build: ./backend
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
      - backend_data:/root/.m2
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/tqs_hw1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8080/actuator/health || exit 1
      interval: 2s
      timeout: 30s
      retries: 200
      start_period: 10s
    networks:
      - backend
      - frontend

  frontend:
    build: ./frontend
    restart: on-failure
    ports:
      - 3030:3030
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app
      - modules:/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030"]
      interval: 1s
      timeout: 5s
      retries: 20
    networks:
      - frontend

volumes:
  db_file:
  modules:
  backend_data:

networks:
  backend:
  frontend: